## Задание 1: Создание и манипуляции с тензорами

In [5]:
import torch

### 1.1 Создание тензоров

Создайте следующие тензоры:
1) Тензор размером 3x4, заполненный случайными числами от 0 до 1
2) Тензор размером 2x3x4, заполненный нулями
3) Тензор размером 5x5, заполненный единицами
4) Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

In [6]:
# 1) Тензор размером 3x4, заполненный случайными числами от 0 до 1
rand_tensor = torch.rand(3, 4)
print(rand_tensor)

tensor([[0.1310, 0.3668, 0.7440, 0.7981],
        [0.7130, 0.5242, 0.9143, 0.2573],
        [0.5771, 0.9701, 0.9154, 0.5376]])


In [7]:
# 2) Тензор размером 2x3x4, заполненный нулями
zeros_tensor = torch.zeros(2,3,4)
print(zeros_tensor) 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
# 3) Тензор размером 5x5, заполненный единицами
ones_tensor = torch.ones(5,5)
print(ones_tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [9]:
# 4) Тензор размером 4x4 c числами от 0 до 15 (использовать reshape)
x_tensor = torch.arange(16).reshape(4,4)
print(x_tensor)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


### 1.2 Операции с тензорами

*Дано:* тензор A размером 3x4 и тензор B размером 4x3 

*Выполните:*

1) Транспонирование тензора A
2) Матричное умножение A и B
3) Поэлементное умножение A и транспонированного B
4) Вычислите сумму всех элементов тензора A

In [10]:
A = torch.arange(12).reshape(3,4)
B = torch.arange(12).reshape(4,3)

print(f'A tensor: \n {A}\n')
print(f'B tensor: \n {B}')

A tensor: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

B tensor: 
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [11]:
# 1) Транспонирование тензора A
print(f'A transposed: \n {A.T}')

A transposed: 
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


In [12]:
# 2) Матричное умножение A и B
print(f'A matmul B: \n {A @ B}')

A matmul B: 
 tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])


In [13]:
# 3) Поэлементное умножение A и транспонированного B
print(f'A mul B.T: \n {A * B.T}')

A mul B.T: 
 tensor([[  0,   3,  12,  27],
        [  4,  20,  42,  70],
        [ 16,  45,  80, 121]])


In [14]:
# 4) Вычислите сумму всех элементов тензора A
print(A.sum())

tensor(66)


### 1.3 Индексация и срезы

Создайте тензор размером 5x5x5. Извлеките:

1) Первую строку
2) Последний столбец
3) Подматрицу размером 2x2 из центра тензора
4) Все элементы с четными индексами

In [16]:
tensor = torch.arange(125).reshape(5,5,5)
tensor

tensor([[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24]],

        [[ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74]],

        [[ 75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124]]])

Если под строкой в данном контексте понимать второе измерение (ось 1), то первая строка - это `tensor[i, 0]` для любого `i`. Например, для первой матрицы `tensor[0]`:

In [17]:
# 1) Первая строка
tensor[0, 0]

tensor([0, 1, 2, 3, 4])

Если под столбцом понимается последнее измерение (ось 2), то последний столбец - это `tensor[i, :, -1]` для любого `i`. Например, для последней матрицы `tensor[-1]`:

In [18]:
# 2) Последний столбец
tensor[-1, :, -1]

tensor([104, 109, 114, 119, 124])

In [19]:
# 3) Подматрица размером 2x2 из центра тензора
center_depth = tensor.shape[0] // 2
center_row = tensor.shape[1]  // 2
center_col = tensor.shape[2] // 2

tensor[center_depth, 
       center_row-1:center_row+1,
       center_col-1:center_col+1]

tensor([[56, 57],
        [61, 62]])

In [20]:
# 4) Все элементы с чётными индексами
tensor[::2, ::2, ::2]

tensor([[[  0,   2,   4],
         [ 10,  12,  14],
         [ 20,  22,  24]],

        [[ 50,  52,  54],
         [ 60,  62,  64],
         [ 70,  72,  74]],

        [[100, 102, 104],
         [110, 112, 114],
         [120, 122, 124]]])

### 1.4 Работа с формами

Создайте тензор размером 24 элемента. Преобразуйте его в формы:

1) 2x12
2) 3x8
3) 4x6
4) 2x3x4
5) 2x2x2x3

In [21]:
tensor = torch.arange(24)
tensor

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [22]:
# 1) 2x12
tensor.reshape(2,12)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [23]:
# 2) 3x8
tensor.reshape(3,8)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
# 3) 4x6
tensor.reshape(4,6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [25]:
# 4) 2x3x4
tensor.reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [26]:
# 5) 2x2x2x3
tensor.reshape(2,2,2,3)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])